# Generated by Django 3.2 on 2022-07-02 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0003_auto_20220701_1155'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userscore',
            options={'permissions': [('Has_score_permission', 'user has score permission')]},
        ),
    ]
